= Реализация RPC протокола с использованием aiohttp и sqlalchemy-core


== Запуск:

* Склонировать репозиторий к себе, перейти в созданную директорию
* Создать файл с конфигами и заполнить его:
+
[source, bash]
----
cp config_example.py config.py
----
При старте сервиса создадутся все таблицы, поэтому лучше создать тестовую базу в postgres и указать всё необходимое для подключения к ней

* Создать виртуальное окружения, активировать, установить зависимости:
+
[source, bash]
----
virtualenv .env -p python3.8
source .env/bin/activate
pip install -r requirements.txt
----

* Далее перейти в папку app и запустить сервис через manage.py с флагом -r
+
[source, bash]
----
cd app
python manage.py -r
----

* Для того, чтобы создать все таблицы, использовать флаг -m. !!Внимание это действие приведет к удалению всех ранее созданных таблиц связанных с проектом из БД и создания их заново. Все данные будут утеряны !!
+
[source, bash]
----
python manage.py -m
----

== Доступ к RPC

Все запросы необходимо отправлять на http://127.0.0.1:8000/rpc. Поддерживается только post запросы с content-type application/json!
Формат тела запроса выглядит следующим образом:
[source, json]
----
{
  "method": "string",
  "params": "object"
}
----
В method указывается процедура, которую необходимо вызвать, в params указываются необходимые дополнительные параметры. Ответ приходит в виде json объекта.

=== get_document_by_id
Получение данных документа по id

Пример запроса:
[source, json]
----
{
  "method": "get_document_by_id",
  "params": {
    "id": 1
  }
}
----
Пример ответа:
[source, json]
----
{
    "id": 1,
    "name": "Отчет",
    "created_at": "2021-03-28 17:14:48",
    "updated_at": "2021-03-28 17:39:16"
}
----

=== create_document
Создает документ в БД и возвращает данные созданного документа

Пример запроса:
[source, json]
----
{
  "method": "create_document",
  "params": {
    "name": "Отчет 2"
  }
}
----
Пример ответа:
[source, json]
----
{
    "id": 6,
    "name": "Отчет 2",
    "created_at": "2021-03-28 18:10:15",
    "updated_at": "2021-03-28 18:10:15"
}
----


=== update_document
Обновляет данные документа по его id и возвращает данные измененного документа

Пример запроса:
[source, json]
----
{
  "method": "update_document",
  "params": {
    "id": 6,
    "name": "Отчет 21"
  }
}
----
Пример ответа:
[source, json]
----
{
    "id": 6,
    "name": "Отчет 21",
    "created_at": "2021-03-28 18:10:15",
    "updated_at": "2021-03-28 18:12:36"
}
----


=== delete_document
Удаляет документ по id и возвращает данные удаленного документа

Пример запроса:
[source, json]
----
{
  "method": "delete_document",
  "params": {
    "id": 6
  }
}
----
Пример ответа:
[source, json]
----
{
    "id": 6,
    "name": "Отчет 21",
    "created_at": "2021-03-28 18:10:15",
    "updated_at": "2021-03-28 18:12:36"
}
----

=== get_documents
Выводит список всех документов, отсортированный по дате обновления

Пример запроса:
[source, json]
----
{
  "method": "get_documents",
  "params": {}
}
----
Пример ответа:
[source, json]
----
[
    {
        "id": 2,
        "name": "Order",
        "created_at": "2021-03-28 17:14:49",
        "updated_at": "2021-03-28 17:14:49"
    },
    {
        "id": 3,
        "name": "Order",
        "created_at": "2021-03-28 17:14:49",
        "updated_at": "2021-03-28 17:14:49"
    },
    {
        "id": 4,
        "name": "aaaa",
        "created_at": "2021-03-28 17:14:50",
        "updated_at": "2021-03-28 17:14:50"
    },
    {
        "id": 1,
        "name": "ddddd",
        "created_at": "2021-03-28 17:14:48",
        "updated_at": "2021-03-28 17:39:16"
    }
]
----
